### PR TITLE
refactor: separation of translation functionality into the Translation class

### PR DESCRIPTION
**Pull request by sgcr**
1. changes proposed in this pull request:
 - separation of translation functionality with the new Translator class: added constants that were used at several places
 - moved the translations files from the sub-directory 'sprache' to 'language' because it means language
 - renamed the language 'Deutsch.properties' to 'German.properties' corresponding to all other language files that are named in english

2. `src/main/resources/release_notes.md` ...
 - [x] does not require update

### CODE REVIEW

**Review by wsbrenk — COMMENTED** [review]
Welcome to the HO world as a developer. These changes look very good. I noticed a small thing. The language setting of my HO changed from German to English. Could this be changed so that such a setting is automatically set to the new "german"?

**Comment by sgcr** [comment]
Thanks :)

Yes, of course. Will be added for compatibility.

**Comment by sgcr** [comment]
Still not finished due to other findings of my change.

**Comment by sgcr** [comment]
UserParameter  reads the legacy language now and converts it.

Ready to merge from my side.

Should I always squash the commits or is there an option for you?

**Review by wsbrenk — APPROVED** [review]
great work - I am happy about your support!
I prefer squashing when completing the pull request

**Pull request merged**
