### PR TITLE
#1941 repair failed V5 database update

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:

   - fixes issue #1941
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)

2. `src/main/resources/release_notes.md` ...

 - [x] has been updated
 - [ ] does not require update

3. [Optional] suggested person to review this PR @tychobrailleur

### CODE REVIEW

**Comment by tychobrailleur** [comment]
Did it fail for just 500 updates, or also subsequent ones?  Do you think there are other databases out there with similar issues?

This reminds me that a long time ago, I had started a [HO DB Repair](https://github.com/tychobrailleur/hodb-repair) tool which was trying to solve that kind of problems more generically, but it is way out of date, at this point.

**Comment by wsbrenk** [comment]
In case of #1242, i only found missing database components of the v5 update. This change will help the reporter to repair his database - i have no idea if there are other users with the same issue.
So a more generic solution of this issue would be helpful and would override this changes.

What do you think about a solution which describes the database table and a database init method, that will compare the existing table with this description and invokes the necessary changes?

**Comment by wsbrenk** [comment]
Forget it - this idea won't work in all circumstances. Some historical changes could be lost that will lead to not acceptable data loss.

**Comment by tychobrailleur** [comment]
> What do you think about a solution which describes the database table and a database init method, that will compare the existing table with this description and invokes the necessary changes?

Another approach could be to ignore versions for database schema updates, and apply them at startup if they haven't been yet, regardless of version (not sure what startup penalty this would cause, however).  That and make sure changes are backward compatible (i.e. no table or column drop, no rename, etc.).

A long time ago I had suggested to use database migrations (like Flyway or liquibase) to deal with those database changes, this could be another approach, but that's perhaps a bit overkill.

**Review by tychobrailleur — APPROVED** [review]

**Pull request merged**
