### PR TITLE
[BUG] #2139: Fix wrong translation for Spanish for 'worstOfSeason'

### PR DESCRIPTION
**Pull request by sgcr**
1. changes proposed in this pull request:
- fixes issue #2139

2. `src/main/resources/release_notes.md` ...
- [x] has been updated

3. [Optional] suggested person to review this PR @wsbrenk
I've made the changes also in POEditor...

### CODE REVIEW

**Comment by tychobrailleur** [comment]
If you've made the change to POEditor, would you mind reverting the change to the properties file in the code file (but keep the release note entry)?  Just to avoid potential conflicts in the future.  Thanks!

**Comment by tychobrailleur** [comment]
If you've made the change to POEditor, would you mind reverting the change to the properties file in the codebase (but keep the release note entry)?  Just to avoid potential conflicts in the future.  Thanks!

**Review by wsbrenk — CHANGES_REQUESTED** [review]
poeditor integration is working again - so all translations should be done in poeditor now

New terms of the english properties file will be uploaded automatically to poeditor.

I would suggest to close this pr.

**Comment by sgcr** [comment]
> poeditor integration is working again - so all translations should be done in poeditor now
> 
> New terms of the english properties file will be uploaded automatically to poeditor.
> 
> I would suggest to close this pr.

Only `release_notes.md` is updated.
Can be merged.

**Review by tychobrailleur — APPROVED** [review]

**Pull request merged**
