### PR TITLE
Feature/groovy

### PR DESCRIPTION
**Pull request by wsbrenk**
1. changes proposed in this pull request:

implement a groovy api to override the default rating prediction (schum)
the current TestRatingPredictionModel.groovy only returns the constant value 1.
the existing models can be selected in lineup simulation panel.

TODOs: 
* add the override options to the TestRatingPredictionModel.groovy
* implement the old prediction model as groovy model.

@tychobrailleur again i'm learning a new programming language (groovy). i'm still not very familiar with it. Can you help with the TODOs or do you have better ideas?

### CODE REVIEW

**Comment by tychobrailleur** [comment]
> @tychobrailleur again i'm learning a new programming language (groovy). i'm still not very familiar with it. Can you help with the TODOs or do you have better ideas?

Ah funny, I was going to suggest to do something with Kotlin to see if this could become the new HO language (as this also could help with mobile development), but I have done a lot of groovy in the past, so I should be able to help.  

Not sure I get the TODOs, but I need to look at the PR first.

**Comment by tychobrailleur** [comment]
>     * add the override options to the TestRatingPredictionModel.groovy

I am still unsure as to what you mean by override options? 
> 
>     * implement the old prediction model as groovy model.

IS this in the code somewhere?

**Comment by wsbrenk** [comment]
in the last commit i added the protected calculation methods of the RatingPredictionModel as comments to the Test implementation. This methods are intended to be overriden by groovy implementations.

the previous implementation of rating calculation was in the class RatingPredictionManager (see branch release/7). The algorithm is not easy to understand. There are parameter files that describe a list of coefficients that could be used to modify the formulas.

**Comment by wsbrenk** [comment]
@tychobrailleur  now i started my first groovy implementation: AkasolacePredictionModel is trying to recover the current/old rating prediction. 
there are still discrepancies in the results. 
Concerning team spirit in lineup rating simulator: Only  SUB=min (0) are in V7.3 and V8 identical.

SUB | HO7|HO8
-|-|-
min|0|0
low|0.2|0.25
Average/Durchschnitt|0.4|-
high|0.6|0.5
max|0.8|0.75

**Comment by wsbrenk** [comment]
now the results of the groovy class AkasolaceRatingPredictionModel fits quite well to the numbers of HO7.

**Comment by wsbrenk** [comment]
@tychobrailleur what just came to my mind: Could it be that the installer needs to be changed in order for the groovy api to work?

**Comment by tychobrailleur** [comment]
> @tychobrailleur what just came to my mind: Could it be that the installer needs to be changed in order for the groovy api to work?

It shouldn't.  It is a JVM language, so it should work as is.  Are you compiling groovy into bytecode, or is it interpreted?

**Comment by wsbrenk** [comment]
> It shouldn't. It is a JVM language, so it should work as is. 

Great!

> Are you compiling groovy into bytecode, or is it interpreted?

The intention is that the groovy class are interpreted.

> Is your plan to use groovy for new devs? And/or migrate existing code?

The previous implementation uses a list of config files to make the formulas configurable. The options were extremely limited. That's what I wanted to improve with the groovy api.

**Comment by wsbrenk** [comment]
Just looked at it - it looks very promising. It would be great if we could get more developer support through this.

**Comment by tychobrailleur** [comment]
> Just looked at it - it looks very promising. It would be great if we could get more developer support through this.

I spent a few minutes trying to see how hard this could be, I have created a new branch, and converted the `HRF` class into Kotlin:
https://github.com/ho-dev/HattrickOrganizer/compare/master...feature/kotlin_support

This compiles directly into Java bytecode, so no magic required at runtime.

Looks a bit longer to compile, but ultimately the benefits would be:
- a cool language to work with, possibly with some cleanups
- Kotlin is the de facto standard language for Android apps, so that could be a possible bridge

Not sure about attractiveness for developers, but I for one would love working with it. :-)

**Comment by tychobrailleur** [comment]
I made good progress this weekend, migrating all the db code to Kotlin:
https://github.com/ho-dev/HattrickOrganizer/compare/master...tychobrailleur:HO-t:feature/kotlin_support_with_hist?expand=1 -- I have been trying to preserve git history in the process...

I have uncovered a couple of bugs thanks to the good handling of NPE, really enjoying the experience so far.

**Pull request merged**
