### PR TITLE
Use SwingWorker to properly fix hanging UI.

### PR DESCRIPTION
**Pull request by tychobrailleur**
Finally fix properly the hanging Swing UI when downloading the matches in the Team Analyzer tab.

1. changes proposed in this pull request:

cf. above

2. `src/main/resources/release_notes.md` ...

 - [ ] has been updated
 - [x] does not require update

3. [Optional] suggested person to review this PR @wsbrenk

### CODE REVIEW

**Comment by wsbrenk** [comment]
@tychobrailleur  Should this request replace #2056? If so, please change the target branch: Not master, but release/8. And please pick the changes of the release notes (translation support).

**Comment by tychobrailleur** [comment]
No, it completes your PR in #2056 , but your PR is still the main fix for this issue.

**Comment by tychobrailleur** [comment]
Point taken for the target branch, though!

**Review by wsbrenk — APPROVED** [review]
looks good

**Pull request merged**
