### PR TITLE
fix: property 'window.about.text': adding homogeneous line break afte…

### PR DESCRIPTION
**Pull request by sgcr**
I saw in the UI in the "Help"/"About" dialog that the text pointing to the start of the project started looks different in other languages.
To make it homogeneous like in the base language English I added a line break to all other languages where it was missing.

Additionally I corrected the years for danish because there were different years,

### CODE REVIEW

**Review by wsbrenk — CHANGES_REQUESTED** [review]
Good idea,  But these files are overwritten by the poeditor files when building by the github action.

So these changes need to be included in the poeditor project.

Maybe we can also make two entries out of it and hardcode the line break.

**Comment by sgcr** [comment]
> Good idea,  But these files are overwritten by the poeditor files when building by the github action.
> 
> So these changes need to be included in the poeditor project.
> 
> Maybe we can also make two entries out of it and hardcode the line break.

I will have a look poeditor.

**Comment by sgcr** [comment]
> > Good idea,  But these files are overwritten by the poeditor files when building by the github action.
> > So these changes need to be included in the poeditor project.
> > Maybe we can also make two entries out of it and hardcode the line break.
> 
> I will have a look at poeditor.

I signed up for an account at poeditor and waiting for approval for HO.

**Comment by sgcr** [comment]
Waiting for approval for the other language I want to modify...

**Comment by sgcr** [comment]
The same translations in that PR were made in poeditor.

I think this PR can be closed now.

**Pull request closed without merging**
